cookbook "apt"
cookbook "openssl"
cookbook "apache2"
cookbook "mysql"
cookbook "php"
cookbook "git"
cookbook "chef-php-extra", git: "git://github.com/inviqa/chef-php-extra.git"
cookbook "docker"
#cookbook "mongodb"
cookbook "vHost-cookbook", path: "vHost-cookbook"